### ISSUE TITLE
Apply damage button not working

### ISSUE THREAD

**Issue by sroakjp** [javierriveracastro/betteroll-swade#398]
Gives the following error in the console:

Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'label')
[Detected 1 package: betterrolls-swade2]
    at apply_status (cards_common.js:1354:58)
    at apply_damage (damage_card.js:145:11)
    at create_damage_card (damage_card.js:28:33)
    at HTMLButtonElement.<anonymous> (item_card.js:262:8)
    at HTMLButtonElement.dispatch (jquery.min.js:2:43064)
    at HTMLButtonElement.v.handle (jquery.min.js:2:41048)
apply_status @ cards_common.js:1354
apply_damage @ damage_card.js:145
create_damage_card @ damage_card.js:28
(anonymous) @ item_card.js:262
dispatch @ jquery.min.js:2
v.handle @ jquery.min.js:2
Promise.then (async)
(anonymous) @ item_card.js:264
dispatch @ jquery.min.js:2
v.handle @ jquery.min.js:2

**Comment by sroakjp** [comment]
Upon further investigation: Appears to be a conflict with Combat Utility Belt. With that module turned off the apply button appears to work.

**Comment by javierriveracastro** [comment]
To use CUB with swade 1.x you should not modify the status provided by system.
